name: Release Maven

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Release Maven
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Get Git Changelog
        id: get_changelog
        uses: thenilsdev/git-log-action@1.0.2
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
          MAVEN_REPO_USER: ${{ secrets.MAVEN_REPO_USER }}
          MAVEN_REPO_PASS: ${{ secrets.MAVEN_REPO_PASS }}
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.get_changelog.outputs.log }}
      - name: Upload artifacts to release
        id: upload_release_asset
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./artifacts/*.jar"]'
      - name: Notify discord
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_RELEASE_WEBHOOK }}
          nodetail: true
          title: New release of ${{ github.event.repository.name }}
          description: |
            Version `${{ steps.get_changelog.outputs.latestTag }}`
            Click [here](${{ steps.create_release.outputs.html_url }}) to view!

            ${{ steps.get_changelog.outputs.markdownLog }}
      - uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_RELEASE_WEBHOOK }}